import type { Product } from '../../domain/entities/Product';

/**
 * Catálogo técnico base de rodamientos (serie 62xx / 63xx).
 * Medidas estándar ISO — no inventar aplicaciones de vehículo sin verificar.
 */
export const bearingCatalog: Product[] = [
  {
    id: 'brg-6201',
    sku: '6201',
    name: 'Rodamiento 6201',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6201.',
    active: true,
    tags: ['6201', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 12,
      odMm: 32,
      widthMm: 10,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6201', '6201-ZZ', '6201-2RS'],
      applications: ['Motores eléctricos pequeños', 'Poleas', 'Equipos ligeros'],
    },
  },
  {
    id: 'brg-6202',
    sku: '6202',
    name: 'Rodamiento 6202',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6202.',
    active: true,
    tags: ['6202', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 15,
      odMm: 35,
      widthMm: 11,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6202', '6202-ZZ', '6202-2RS'],
      applications: ['Motores eléctricos', 'Bombas', 'Máquinas herramientas'],
    },
  },
  {
    id: 'brg-6203',
    sku: '6203',
    name: 'Rodamiento 6203',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6203.',
    active: true,
    tags: ['6203', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 17,
      odMm: 40,
      widthMm: 12,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6203', '6203-ZZ', '6203-2RS'],
      applications: ['Alternadores', 'Motores', 'Equipos industriales ligeros'],
    },
  },
  {
    id: 'brg-6204',
    sku: '6204',
    name: 'Rodamiento 6204',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6204.',
    active: true,
    tags: ['6204', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 20,
      odMm: 47,
      widthMm: 14,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6204', '6204-ZZ', '6204-2RS'],
      applications: ['Motores eléctricos', 'Reductores', 'Ventiladores'],
    },
  },
  {
    id: 'brg-6205',
    sku: '6205',
    name: 'Rodamiento 6205',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6205.',
    active: true,
    tags: ['6205', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 25,
      odMm: 52,
      widthMm: 15,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6205', '6205-ZZ', '6205-2RS'],
      applications: ['Motores eléctricos', 'Bombas', 'Transmisiones ligeras'],
    },
  },
  {
    id: 'brg-6205-2rs',
    sku: '6205-2RS',
    name: 'Rodamiento 6205-2RS',
    category: 'rodamientos',
    description: 'Rodamiento 6205 con sellos de caucho a ambos lados (2RS).',
    active: true,
    tags: ['6205', '2RS', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 25,
      odMm: 52,
      widthMm: 15,
      sealType: '2RS',
      lubrication: 'Preengrase de fábrica; sello de contacto',
      equivalences: ['6205-2RS', '6205 2RS', '6205 DDU'],
      applications: ['Ambientes con polvo o humedad', 'Motores', 'Equipos generales'],
    },
  },
  {
    id: 'brg-6205-zz',
    sku: '6205-ZZ',
    name: 'Rodamiento 6205-ZZ',
    category: 'rodamientos',
    description: 'Rodamiento 6205 con protectores metálicos (ZZ).',
    active: true,
    tags: ['6205', 'ZZ', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 25,
      odMm: 52,
      widthMm: 15,
      sealType: 'ZZ',
      lubrication: 'Preengrase de fábrica; protector metálico',
      equivalences: ['6205-ZZ', '6205 ZZ', '6205-2Z'],
      applications: ['Motores eléctricos', 'Aplicaciones de alta velocidad relativa'],
    },
  },
  {
    id: 'brg-6206',
    sku: '6206',
    name: 'Rodamiento 6206',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6206.',
    active: true,
    tags: ['6206', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 30,
      odMm: 62,
      widthMm: 16,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6206', '6206-ZZ', '6206-2RS'],
      applications: ['Motores', 'Bombas', 'Maquinaria industrial'],
    },
  },
  {
    id: 'brg-6207',
    sku: '6207',
    name: 'Rodamiento 6207',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6207.',
    active: true,
    tags: ['6207', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 35,
      odMm: 72,
      widthMm: 17,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6207', '6207-ZZ', '6207-2RS'],
      applications: ['Motores industriales', 'Reductores'],
    },
  },
  {
    id: 'brg-6208',
    sku: '6208',
    name: 'Rodamiento 6208',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6208.',
    active: true,
    tags: ['6208', 'serie62'],
    bearing: {
      series: '6200',
      boreMm: 40,
      odMm: 80,
      widthMm: 18,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6208', '6208-ZZ', '6208-2RS'],
      applications: ['Motores industriales', 'Equipos pesados ligeros'],
    },
  },
  {
    id: 'brg-6300',
    sku: '6300',
    name: 'Rodamiento 6300',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6300 (sección más robusta).',
    active: true,
    tags: ['6300', 'serie63'],
    bearing: {
      series: '6300',
      boreMm: 10,
      odMm: 35,
      widthMm: 11,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6300', '6300-ZZ', '6300-2RS'],
      applications: ['Cargas mayores que serie 62 equivalente'],
    },
  },
  {
    id: 'brg-6301',
    sku: '6301',
    name: 'Rodamiento 6301',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6301.',
    active: true,
    tags: ['6301', 'serie63'],
    bearing: {
      series: '6300',
      boreMm: 12,
      odMm: 37,
      widthMm: 12,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6301', '6301-ZZ', '6301-2RS'],
      applications: ['Motores', 'Maquinaria ligera-media'],
    },
  },
  {
    id: 'brg-6302',
    sku: '6302',
    name: 'Rodamiento 6302',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6302.',
    active: true,
    tags: ['6302', 'serie63'],
    bearing: {
      series: '6300',
      boreMm: 15,
      odMm: 42,
      widthMm: 13,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6302', '6302-ZZ', '6302-2RS'],
      applications: ['Motores', 'Bombas', 'Industria general'],
    },
  },
  {
    id: 'brg-6303',
    sku: '6303',
    name: 'Rodamiento 6303',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6303.',
    active: true,
    tags: ['6303', 'serie63'],
    bearing: {
      series: '6300',
      boreMm: 17,
      odMm: 47,
      widthMm: 14,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6303', '6303-ZZ', '6303-2RS'],
      applications: ['Motores eléctricos', 'Reductores'],
    },
  },
  {
    id: 'brg-6304',
    sku: '6304',
    name: 'Rodamiento 6304',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6304.',
    active: true,
    tags: ['6304', 'serie63'],
    bearing: {
      series: '6300',
      boreMm: 20,
      odMm: 52,
      widthMm: 15,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6304', '6304-ZZ', '6304-2RS'],
      applications: ['Motores', 'Maquinaria industrial'],
    },
  },
  {
    id: 'brg-6305',
    sku: '6305',
    name: 'Rodamiento 6305',
    category: 'rodamientos',
    description: 'Rodamiento rígido de bolas serie 6305.',
    active: true,
    tags: ['6305', 'serie63'],
    bearing: {
      series: '6300',
      boreMm: 25,
      odMm: 62,
      widthMm: 17,
      sealType: 'open',
      lubrication: 'Grasa o aceite según aplicación',
      equivalences: ['6305', '6305-ZZ', '6305-2RS'],
      applications: ['Motores industriales', 'Cargas medias'],
    },
  },
];
